import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  main: {
    flex: 1,
    backgroundColor: '#ffff',
  },
  subContainer: {
    backgroundColor: '#6819E6',
    borderBottomLeftRadius: 16,
    borderBottomEndRadius: 16,
    flex: 0.3,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: '20%',
    width: '100%',
  },
  title: {
    marginTop: '3%',
    fontSize: 20,
    color: '#ffff',
    fontWeight: '800',
  },
  shareIcon: {
    resizeMode: 'contain',
    width: 15,
    height: 15,
    position: 'absolute',
    left: 120,
  },
  card: {
    width: '90%',
    height: 500,
    backgroundColor: 'white',
    position: 'absolute',
    top: '30%',
    borderRadius: 15,
    alignSelf: 'center',
    shadowColor: 'black',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 4,
  },
  loanVerifyLogo: {
    resizeMode: 'contain',
    width: '60%',
    height: '60%',
    alignSelf: 'center',
    bottom: '12%',
  },
  verifyTilteTxt: {
    color: '#6819E6',
    fontSize: 20,
    fontWeight: 'bold',
    bottom: '25%',
    textAlign: 'center',
  },
  detailsContainer: {
    paddingHorizontal: '5%',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    height: '10%',
    bottom: '25%',
  },
  detailsText: {
    fontSize: 14,
    color: '#000',
    fontWeight: 'bold',
  },
  verifyContainer: {
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexDirection: 'row',
    width: '30%',
    height: '100%',
    gap: '5%',
  },
  verifiedText: {
    fontSize: 14,
    color: '#000',
    fontWeight: 'bold',
  },
  verifyLogo: {
    resizeMode: 'contain',
    width: 15,
    height: 30,
  },
  checkboxContainer: {
    width: '100%',
    height: '5%',
    bottom: '20%',
    alignItems: 'center',
    paddingHorizontal: '4%',
    justifyContent: 'center',
  },
  checkboxTouch: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkboxIcon: {
    resizeMode: 'contain',
    width: 16,
    height: 16,
  },
  termsText: {
    fontSize: 13,
    color: '#8cdbefff',
    marginLeft: 8,
  },
  touchBtn: {
    width: '85%',
    height: '16%',
    marginTop: '132%',
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: '#6819E6',
    shadowColor: '#6819E6',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 4,
  },
  btnText: {
    color: '#ffff',
    fontSize: 20,
    fontWeight: '700',
  },
});
