import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  headerView: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 50,
    marginTop: 10,
    width: '100%',
    marginBottom: 8,
  },
  touchProfile: {
    backgroundColor: '#6819E6',
    width: 30,
    height: 30,
    marginLeft: 20,
    borderRadius: 40,
  },
  searchBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f4f4f4',
    borderRadius: 30,
    paddingHorizontal: 10,
    borderColor: 'gray',
    borderWidth: 1,
    height: 40,
    marginHorizontal: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: 'gray',
  },
  searchIcon: {
    width: 30,
    height: 30,
    backgroundColor: '#6819E6',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
  },
  touchNotify: {
    backgroundColor: '#6819E6',
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
    marginRight: 20,
  },
  allLoansRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
    marginLeft: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginRight: 8,
  },
  loanGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 5,
    justifyContent: 'center',
    gap: 12,
  },
  dashBopardView: {
    width: '90%',
    marginTop: 20,
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    // shadowColor: 'black',
    // shadowOffset: {
    //   width: 0,
    //   height: 15,
    // },
    // shadowOpacity: 1,
    // shadowRadius: 10,
    // elevation: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'gray',
    alignSelf: 'center',
    paddingHorizontal: 15,
  },
  dashboardText: {
    color: 'black',
    fontWeight: 'bold',
  },
  dashboardLogo: {
    resizeMode: 'contain',
    height: 32,
    width: 32,
  },
  cardPurple: {
    backgroundColor: '#d4c9f3ff',
    padding: 16,
    width: '100%',
    marginTop: 15,
    marginBottom: 14,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 6,
  },
  cardDesc: {
    fontSize: 11,
    color: '#555',
  },
  magnifyLogo: {
    resizeMode: 'contain',
    width: 140,
    height: 140,
    position: 'absolute',
    right: 18,
  },
  btnArrow: {
    backgroundColor: '#9770e0ff',
    borderRadius: 20,
    width: 80,
    height: 23,
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-start',
    marginTop: 10,
  },
  faqCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#ffff',
    borderRadius: 10,
    marginHorizontal: 20,
    padding: 14,
    marginBottom: 16,
    shadowColor: 'black',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 6,
  },
  faqText: {
    fontWeight: '600',
    fontSize: 15,
  },
  faqLogo: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
    marginTop: 6,
  },
  headerTitle: {
    fontSize: 18,
    marginTop: 5,
    fontWeight: '700',
    marginLeft: 20,
    marginRight: 4,
  },
  headerLine: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
  },
  lineBold: {
    flex: 1,
    height: 2,
    backgroundColor: '#6819F6',
  },
  lineThin: {
    flex: 2,
    height: 1,
    backgroundColor: '#C5A9F6',
    marginLeft: 4,
  },
  stepRow: {
    flexDirection: 'row',
    marginBottom: 24,
    marginTop: -10,
  },
  left: {
    alignItems: 'center',
    width: 40,
    marginLeft: 10,
  },
  circle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#6819F6',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    zIndex: 1,
  },
  circleText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#191522ff',
  },
  dottedLine: {
    flex: 1,
    width: 2,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: '#6819F6',
    // marginTop: 2,
  },
  right: {
    flex: 1,
    paddingLeft: 8,
  },
  stepTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  stepDesc: {
    fontSize: 12,
    color: '#555',
  },
});
